### ISSUE TITLE
update workspace variable to 10.3

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/NHA#1]
The tool was erroring out due to the lack of a pnhp.[user].sde connection file in the folder the workspace variable. Variable should be updated to 10.3--actionally, can we make the tool reference the latest arcgis version.

ex)
Executing: CreateNHAv2 "Mohn Mill Ponds" "Union Update 2015" "Conservation Planning Polygons\CPP_Core" true
Start Time: Thu Oct 01 10:47:54 2015
Running script CreateNHAv2...

Traceback (most recent call last):
  File "<string>", line 307, in execute
  File "<string>", line 232, in check_edit_session
RuntimeError: cannot open workspace

Failed to execute (CreateNHAv2).
Failed at Thu Oct 01 10:48:11 2015 (Elapsed Time: 16.24 seconds)

**Comment by dyeany** [comment]
The user running the Create NHA – Version 2 tool must establish a direct connection to his or her version of the database through Database Connections in ArcCatalog. I updated the script with a header note that this must be done. The steps to ensure this are:
1)	Add Database Connection in ArcCatalog for PNHP
2)	Rename new connection to ‘PNHP.username.pgh-gis.sde’
3)	Right-click on ‘PNHP.username.pgh-gis.sde’ and select Geodatabase Connection Properties
4)	Select the correct user version of the database from the list and click OK.

This should prevent future workspace errors from occurring.
